### ISSUE TITLE
Weird: Does this not allow overwriting the file over and over again.

### ISSUE THREAD

**Issue by austinsonger** [GuillaumeFalourd/command-output-file-action#3]
The action log says its writing the file, but I didn't the file before running and it says its wrote it, but the file doesn't exist.

https://github.com/austinsonger/automate-aws-evidence-collection/actions/runs/4703116276/jobs/8341214663

**Comment by GuillaumeFalourd** [comment]
Hi @austinsonger , how are you doing? 

Thank you for opening this ISSUE!

Where do you expect the file to exist? In the runner during the workflow run, or in the repository after the workflow run?

The action only runs: `{command_line} &> {output_file}`. 
This command should overwrite the current `{output_file}` content if the file exists.

**Comment by austinsonger** [comment]
```
# LIST OF SERVER CERTIFICATES        
      - uses: GuillaumeFalourd/command-output-file-action@main
        with:
         command_line: aws iam list-server-certificates --output yaml
         output_file_name: lists/list-server-certificates.yaml
         display_file_content: YES #  
```


![image](https://user-images.githubusercontent.com/26654315/232141534-5a6c742b-6e75-4c6e-92ed-df83f058f292.png)

**Comment by GuillaumeFalourd** [comment]
```
# LIST OF SERVER CERTIFICATES        
      - uses: GuillaumeFalourd/command-output-file-action@main
        with:
         command_line: aws iam list-server-certificates --output yaml
         output_file_name: lists/list-server-certificates.yaml
         display_file_content: YES #  
```
This specific configuration will return an error if the `lists` folder doesn't exists, as the action doesn't create new folders automatically.

Adding this step should work:
```
      - run: mkdir lists
         shell: bash
      - uses: GuillaumeFalourd/command-output-file-action@main
        with:
         command_line: aws iam list-server-certificates --output yaml
         output_file_name: lists/list-server-certificates.yaml
         display_file_content: YES #  
```
